import { NextResponse } from 'next/server'
import { PrismaClient } from '@prisma/client'

const AIVEN = process.env.DATABASE_URL || ''

export async function GET() {
  try {
    const p = new PrismaClient()
    const r: any = await p.$queryRaw`SELECT 1 as test, NOW() as now`
    await p.$disconnect()
    return NextResponse.json({ ok: true, db: JSON.stringify(r[0]) })
  } catch (e: any) {
    return NextResponse.json({ ok: false, err: e.message.substring(0, 150) })
  }
}

export async function POST() {
  const p = new PrismaClient()
  const out: string[] = []
  const sqls = [
    'CREATE EXTENSION IF NOT EXISTS "pgcrypto"',
    'CREATE TABLE IF NOT EXISTS "Condominio" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "direccion" TEXT, "comuna" TEXT, "ciudad" TEXT, "rut" TEXT, "logo" TEXT, "telefono" TEXT, "email" TEXT, "activo" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Condominio_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "User" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "email" TEXT NOT NULL, "password" TEXT NOT NULL, "nombre" TEXT NOT NULL, "apellido" TEXT, "rol" TEXT NOT NULL DEFAULT \'usuario\', "activo" BOOLEAN NOT NULL DEFAULT true, "telefono" TEXT, "permisos" TEXT, "debeCambiarPassword" BOOLEAN NOT NULL DEFAULT false, "intentosLogin" INTEGER NOT NULL DEFAULT 0, "bloqueadoHasta" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "condominioId" TEXT, "sessionToken" TEXT, "sessionExpiry" TIMESTAMP(3), CONSTRAINT "User_pkey" PRIMARY KEY ("id"), CONSTRAINT "User_email_key" UNIQUE ("email"))',
    'CREATE TABLE IF NOT EXISTS "Session" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "userId" TEXT NOT NULL, "token" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "userAgent" TEXT, "ip" TEXT, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"), CONSTRAINT "Session_token_key" UNIQUE ("token"))',
    'CREATE TABLE IF NOT EXISTS "CentroCostoMaster" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT NOT NULL, "nombre" TEXT NOT NULL, "descripcion" TEXT, "responsable" TEXT, "tipoGasto" TEXT NOT NULL DEFAULT \'Variable\', "presupuestoMens" DOUBLE PRECISION NOT NULL DEFAULT 0, "presupuestoAnual" DOUBLE PRECISION NOT NULL DEFAULT 0, "estado" TEXT NOT NULL DEFAULT \'Activo\', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "condominioId" TEXT, CONSTRAINT "CentroCostoMaster_pkey" PRIMARY KEY ("id"), CONSTRAINT "CentroCostoMaster_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "CatHerramienta" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT, "nombre" TEXT NOT NULL, "marca" TEXT, "modelo" TEXT, "cantidad" INTEGER NOT NULL DEFAULT 1, "ubicacion" TEXT, "estado" TEXT NOT NULL DEFAULT \'Bueno\', "valorReposicion" DOUBLE PRECISION NOT NULL DEFAULT 0, "fechaAdquisicion" TEXT, "descripcion" TEXT, "manualBase64" TEXT, "manualNombre" TEXT, "manualTipo" TEXT, "fechaUltimoMantencion" TEXT, "informeMantencionBase64" TEXT, "informeMantencionNombre" TEXT, "informeMantencionTipo" TEXT, "qrCodigo" TEXT, "condominioId" TEXT, "centroCostoId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CatHerramienta_pkey" PRIMARY KEY ("id"), CONSTRAINT "CatHerramienta_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "CatMaterial" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT, "nombre" TEXT NOT NULL, "unidad" TEXT NOT NULL DEFAULT \'unidad\', "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "categoria" TEXT NOT NULL DEFAULT \'General\', "stockMinimo" INTEGER NOT NULL DEFAULT 0, "stockActual" INTEGER NOT NULL DEFAULT 0, "ubicacion" TEXT, "descripcion" TEXT, "centroCostoId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CatMaterial_pkey" PRIMARY KEY ("id"), CONSTRAINT "CatMaterial_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "CatTarea" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT, "nombre" TEXT NOT NULL, "categoria" TEXT NOT NULL DEFAULT \'General\', "sistema" TEXT, "tipoMantencion" TEXT NOT NULL DEFAULT \'Preventivo\', "frecuencia" TEXT, "responsable" TEXT, "tiempoEstimado" INTEGER NOT NULL DEFAULT 0, "descripcion" TEXT, "condominioId" TEXT, "centroCostoId" TEXT, "esRecurrente" BOOLEAN NOT NULL DEFAULT false, "activa" BOOLEAN NOT NULL DEFAULT true, "proximaEjecucion" TEXT, "ultimaEjecucion" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CatTarea_pkey" PRIMARY KEY ("id"), CONSTRAINT "CatTarea_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "Propiedad" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Casa\', "direccion" TEXT, "estado" TEXT NOT NULL DEFAULT \'Ocupada\', "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Propiedad_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Personal" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "rut" TEXT, "nombre" TEXT NOT NULL, "apellido" TEXT, "cargo" TEXT, "telefono" TEXT, "email" TEXT, "estado" TEXT NOT NULL DEFAULT \'Activo\', "fechaIngreso" TEXT, "tipoContrato" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Personal_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Activo" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT, "nombre" TEXT NOT NULL, "categoria" TEXT NOT NULL DEFAULT \'Equipo\', "estado" TEXT NOT NULL DEFAULT \'Activo\', "ubicacion" TEXT, "serie" TEXT, "fechaCompra" TEXT, "costoCompra" DOUBLE PRECISION NOT NULL DEFAULT 0, "valorActual" DOUBLE PRECISION NOT NULL DEFAULT 0, "descripcion" TEXT, "manualBase64" TEXT, "manualNombre" TEXT, "manualTipo" TEXT, "qrCodigo" TEXT, "fechaUltimoMantencion" TEXT, "informeMantencionBase64" TEXT, "informeMantencionNombre" TEXT, "informeMantencionTipo" TEXT, "condominioId" TEXT, "asignadoId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Activo_pkey" PRIMARY KEY ("id"), CONSTRAINT "Activo_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "Proveedor" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "razonSocial" TEXT NOT NULL, "rut" TEXT, "giro" TEXT, "direccion" TEXT, "comuna" TEXT, "telCorp" TEXT, "emailCorp" TEXT, "web" TEXT, "contacto" TEXT, "cargo" TEXT, "telDirecto" TEXT, "emailContacto" TEXT, "celular" TEXT, "estado" TEXT NOT NULL DEFAULT \'Activo\', "notas" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Proveedor_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "OrdenTrabajo" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "otNum" TEXT NOT NULL, "titulo" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Correctivo\', "prioridad" TEXT NOT NULL DEFAULT \'Media\', "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "ubicacion" TEXT, "fechaInicio" TEXT, "fechaLimite" TEXT, "fechaInicioReal" TEXT, "fechaFinReal" TEXT, "costoEstimado" DOUBLE PRECISION NOT NULL DEFAULT 0, "costoReal" DOUBLE PRECISION NOT NULL DEFAULT 0, "progreso" INTEGER NOT NULL DEFAULT 0, "descripcion" TEXT, "tiempoEst" INTEGER NOT NULL DEFAULT 0, "tiempoReal" INTEGER NOT NULL DEFAULT 0, "valorHora" DOUBLE PRECISION NOT NULL DEFAULT 0, "notas" TEXT, "esRecurrente" BOOLEAN NOT NULL DEFAULT false, "tareaOrigenId" TEXT, "proximaEjecucion" TEXT, "formaPago" TEXT, "estadoAprobacion" TEXT, "fechaSolicitudAprob" TEXT, "fechaAprobacion" TEXT, "aprobadoPor" TEXT, "observacionesAprob" TEXT, "fotosAntes" TEXT, "fotosDespues" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "condominioId" TEXT, "propiedadId" TEXT, "asignadoId" TEXT, "activoId" TEXT, "centroCostoId" TEXT, CONSTRAINT "OrdenTrabajo_pkey" PRIMARY KEY ("id"), CONSTRAINT "OrdenTrabajo_otNum_key" UNIQUE ("otNum"))',
    'CREATE TABLE IF NOT EXISTS "OTMaterial" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "descripcion" TEXT NOT NULL, "cantidad" DOUBLE PRECISION NOT NULL DEFAULT 1, "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "unidad" TEXT NOT NULL DEFAULT \'unidad\', "otId" TEXT NOT NULL, CONSTRAINT "OTMaterial_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "OTHerramienta" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "cantidad" INTEGER NOT NULL DEFAULT 1, "otId" TEXT NOT NULL, CONSTRAINT "OTHerramienta_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "OTTarea" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "descripcion" TEXT NOT NULL, "cantidad" INTEGER NOT NULL DEFAULT 1, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "ok" BOOLEAN NOT NULL DEFAULT false, "noOk" BOOLEAN NOT NULL DEFAULT false, "na" BOOLEAN NOT NULL DEFAULT false, "otId" TEXT NOT NULL, CONSTRAINT "OTTarea_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "OTPersonal" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Interno\', "cantidad" INTEGER NOT NULL DEFAULT 1, "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "horasTrabajadas" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "cumple" BOOLEAN, "observaciones" TEXT, "otId" TEXT NOT NULL, CONSTRAINT "OTPersonal_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "OTDocumento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'documento\', "archivo" TEXT NOT NULL, "otId" TEXT NOT NULL, CONSTRAINT "OTDocumento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Proyecto" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT, "nombre" TEXT NOT NULL, "categoria" TEXT NOT NULL DEFAULT \'General\', "estado" TEXT NOT NULL DEFAULT \'Planificado\', "ubicacion" TEXT, "fechaInicio" TEXT, "fechaFin" TEXT, "presProg" DOUBLE PRECISION NOT NULL DEFAULT 0, "presUsado" DOUBLE PRECISION NOT NULL DEFAULT 0, "avance" INTEGER NOT NULL DEFAULT 0, "descripcion" TEXT, "notas" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "sector" TEXT, "tipoReparacion" TEXT, "tipoTrabajo" TEXT, "prioridad" TEXT, "estadoAprobacion" TEXT, "responsable" TEXT, "responsableExterno" TEXT, "tiempoEstimado" TEXT, "monto" DOUBLE PRECISION NOT NULL DEFAULT 0, "fechaInicioReal" TEXT, "fechaFinReal" TEXT, "comentarios" TEXT, "fotosAntes" TEXT, "fotosDespues" TEXT, "cotizaciones" TEXT, "condominioId" TEXT, "centroCostoId" TEXT, CONSTRAINT "Proyecto_pkey" PRIMARY KEY ("id"), CONSTRAINT "Proyecto_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "ProyectoMaterial" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "descripcion" TEXT NOT NULL, "cantidad" DOUBLE PRECISION NOT NULL DEFAULT 1, "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "unidad" TEXT NOT NULL DEFAULT \'unidad\', "linkCompra" TEXT, "proyectoId" TEXT NOT NULL, CONSTRAINT "ProyectoMaterial_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ProyectoHerramienta" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "cantidad" INTEGER NOT NULL DEFAULT 1, "proyectoId" TEXT NOT NULL, CONSTRAINT "ProyectoHerramienta_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ProyectoTarea" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "descripcion" TEXT NOT NULL, "cantidad" INTEGER NOT NULL DEFAULT 1, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "proyectoId" TEXT NOT NULL, CONSTRAINT "ProyectoTarea_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ProyectoPersonal" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Interno\', "cantidad" INTEGER NOT NULL DEFAULT 1, "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "proyectoId" TEXT NOT NULL, CONSTRAINT "ProyectoPersonal_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ProyectoDocumento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'cotizacion\', "descripcion" TEXT, "archivo" TEXT NOT NULL, "fechaDoc" TEXT, "proyectoId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProyectoDocumento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "SolicitudCompra" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT NOT NULL, "titulo" TEXT NOT NULL, "descripcion" TEXT, "estado" TEXT NOT NULL DEFAULT \'Solicitado\', "prioridad" TEXT NOT NULL DEFAULT \'Media\', "origenTipo" TEXT, "origenId" TEXT, "origenCodigo" TEXT, "materiales" TEXT, "totalEstimado" DOUBLE PRECISION NOT NULL DEFAULT 0, "solicitadoPor" TEXT, "solicitadoPorId" TEXT, "fechaSolicitud" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "fechaEspera" TEXT, "proveedorSugerido" TEXT, "observaciones" TEXT, "links" TEXT, "emailEnviado" BOOLEAN NOT NULL DEFAULT false, "emailEnviadoA" TEXT, "emailFechaEnvio" TIMESTAMP(3), "condominioId" TEXT, "etapaAprobacion" TEXT NOT NULL DEFAULT \'Pendiente Supervisor\', "supervisorAprobadorId" TEXT, "supervisorAprobadorNombre" TEXT, "supervisorFechaAprobacion" TIMESTAMP(3), "supervisorObservaciones" TEXT, "adminAprobadorId" TEXT, "adminAprobadorNombre" TEXT, "adminFechaAprobacion" TIMESTAMP(3), "adminObservaciones" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SolicitudCompra_pkey" PRIMARY KEY ("id"), CONSTRAINT "SolicitudCompra_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "Notificacion" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "titulo" TEXT NOT NULL, "mensaje" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Info\', "categoria" TEXT NOT NULL DEFAULT \'General\', "destino" TEXT NOT NULL DEFAULT \'Todos\', "destinoId" TEXT, "leido" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "condominioId" TEXT, CONSTRAINT "Notificacion_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Gasto" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "descripcion" TEXT NOT NULL, "monto" DOUBLE PRECISION NOT NULL, "fecha" TEXT NOT NULL, "categoria" TEXT NOT NULL DEFAULT \'General\', "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "condominioId" TEXT, "centroCostoId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Gasto_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "CajaChica" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "saldo" DOUBLE PRECISION NOT NULL DEFAULT 0, "saldoInicial" DOUBLE PRECISION NOT NULL DEFAULT 0, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CajaChica_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Configuracion" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "clave" TEXT NOT NULL, "valor" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Configuracion_pkey" PRIMARY KEY ("id"), CONSTRAINT "Configuracion_clave_key" UNIQUE ("clave"))',
    'CREATE TABLE IF NOT EXISTS "Backup" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "tipo" TEXT NOT NULL, "estado" TEXT NOT NULL, "fechaInicio" TIMESTAMP(3), "fechaFin" TIMESTAMP(3), "tamano" DOUBLE PRECISION, "archivo" TEXT, "ubicacion" TEXT, "totalTablas" INTEGER, "totalRegistros" INTEGER, "verificado" BOOLEAN NOT NULL DEFAULT false, "fechaVerificacion" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Backup_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "LogAuditoria" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "userId" TEXT, "userName" TEXT, "accion" TEXT NOT NULL, "modulo" TEXT, "detalle" TEXT, "ip" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LogAuditoria_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Inspeccion" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "titulo" TEXT NOT NULL, "tipo" TEXT NOT NULL DEFAULT \'Mantenimiento\', "estado" TEXT NOT NULL DEFAULT \'Planificado\', "fecha" TEXT, "hora" TEXT, "ubicacion" TEXT, "asignado" TEXT, "descripcion" TEXT, "recurrente" BOOLEAN NOT NULL DEFAULT false, "notas" TEXT, "fotosAntes" TEXT, "fotosDurante" TEXT, "fotosDespues" TEXT, "fotos" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "condominioId" TEXT, CONSTRAINT "Inspeccion_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Ronda" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "descripcion" TEXT, "frecuencia" TEXT NOT NULL DEFAULT \'Diaria\', "hora" TEXT, "activa" BOOLEAN NOT NULL DEFAULT true, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Ronda_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "RegistroRonda" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "rondaId" TEXT NOT NULL, "fecha" TEXT, "hora" TEXT, "usuarioId" TEXT, "usuarioNombre" TEXT, "ubicacion" TEXT, "latitud" DOUBLE PRECISION, "longitud" DOUBLE PRECISION, "observaciones" TEXT, "foto" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RegistroRonda_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ListaVerificacion" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "codigo" TEXT NOT NULL, "nombre" TEXT NOT NULL, "sector" TEXT NOT NULL, "frecuencia" TEXT NOT NULL, "responsable" TEXT NOT NULL, "personalRequerido" TEXT, "descripcion" TEXT, "items" TEXT NOT NULL DEFAULT \'[]\', "activa" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ListaVerificacion_pkey" PRIMARY KEY ("id"), CONSTRAINT "ListaVerificacion_codigo_key" UNIQUE ("codigo"))',
    'CREATE TABLE IF NOT EXISTS "RegistroLV" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "lvId" TEXT NOT NULL, "fecha" TEXT NOT NULL, "hora" TEXT, "responsableEjecucion" TEXT, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "observaciones" TEXT, "itemsCompletados" TEXT, "firmaUrl" TEXT, "fotoUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "RegistroLV_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "SalidaPanol" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "herramientaId" TEXT NOT NULL, "usuarioNombre" TEXT NOT NULL, "usuarioRUT" TEXT, "fechaSalida" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "horaSalida" TEXT NOT NULL, "trabajoRealizar" TEXT, "sectorTrabajo" TEXT, "lvAntesCompletada" BOOLEAN NOT NULL DEFAULT false, "lvAntesItems" TEXT, "lvAntesFirma" TEXT, "fechaIngreso" TIMESTAMP(3), "horaIngreso" TEXT, "estadoDevolucion" TEXT, "comentarios" TEXT, "lvDespuesCompletada" BOOLEAN NOT NULL DEFAULT false, "lvDespuesItems" TEXT, "lvDespuesFirma" TEXT, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SalidaPanol_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "HistorialAprobacionOT" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "otId" TEXT NOT NULL, "estadoAnterior" TEXT, "estadoNuevo" TEXT NOT NULL, "observaciones" TEXT, "aprobadoPor" TEXT, "nombreAprobador" TEXT, "fechaAccion" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HistorialAprobacionOT_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "HistorialAprobacionSC" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "solicitudId" TEXT NOT NULL, "etapaAnterior" TEXT, "etapaNueva" TEXT NOT NULL, "accion" TEXT NOT NULL, "observaciones" TEXT, "aprobadorId" TEXT, "aprobadorNombre" TEXT, "fechaAccion" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HistorialAprobacionSC_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "CategoriaCumplimiento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL, "icono" TEXT, "color" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CategoriaCumplimiento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "DocumentoCumplimiento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "titulo" TEXT NOT NULL, "descripcion" TEXT, "categoriaId" TEXT, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "cumple" BOOLEAN, "fechaVencimiento" TEXT, "archivo" TEXT, "archivoNombre" TEXT, "observaciones" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DocumentoCumplimiento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "HistorialCumplimiento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "documentoId" TEXT NOT NULL, "estado" TEXT NOT NULL, "observaciones" TEXT, "userId" TEXT, "userName" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HistorialCumplimiento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ResumenCumplimiento" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "porcentajeGeneral" INTEGER NOT NULL DEFAULT 0, "totalRequisitos" INTEGER NOT NULL DEFAULT 0, "requisitosCumplidos" INTEGER NOT NULL DEFAULT 0, "requisitosPendientes" INTEGER NOT NULL DEFAULT 0, "requisitosVencidos" INTEGER NOT NULL DEFAULT 0, "alertasActivas" INTEGER NOT NULL DEFAULT 0, "porcentajeLegal" INTEGER NOT NULL DEFAULT 0, "porcentajeReglamentario" INTEGER NOT NULL DEFAULT 0, "porcentajeInterno" INTEGER NOT NULL DEFAULT 0, "porcentajeSeguridad" INTEGER NOT NULL DEFAULT 0, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ResumenCumplimiento_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "HorarioTrabajador" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombreTrabajador" TEXT NOT NULL, "cargo" TEXT, "tipoTurno" TEXT NOT NULL DEFAULT \'5x2\', "horaEntrada" TEXT, "horaSalida" TEXT, "diasTrabajo" TEXT, "diasLibre" TEXT, "activo" BOOLEAN NOT NULL DEFAULT true, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "HorarioTrabajador_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "RegistroAsistenciaReloj" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombreTrabajador" TEXT NOT NULL, "fecha" TEXT NOT NULL, "hora" TEXT, "tipo" TEXT, "diaSemana" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RegistroAsistenciaReloj_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "InasistenciaAtraso" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombreTrabajador" TEXT NOT NULL, "fecha" TEXT NOT NULL, "diaSemana" TEXT, "tipo" TEXT NOT NULL, "horaEsperadaInicio" TEXT, "horaRealInicio" TEXT, "horaEsperadaFin" TEXT, "horaRealFin" TEXT, "minutosAtraso" INTEGER NOT NULL DEFAULT 0, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InasistenciaAtraso_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "JustificacionAsistencia" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "tipoJustificacion" TEXT, "descripcion" TEXT, "archivo" TEXT, "archivoNombre" TEXT, "estado" TEXT NOT NULL DEFAULT \'Pendiente\', "aprobadoPor" TEXT, "nombreAprobador" TEXT, "fechaAprobacion" TEXT, "observaciones" TEXT, "inasistenciaId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "JustificacionAsistencia_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "ListaDesplegable" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "tipo" TEXT NOT NULL, "valor" TEXT NOT NULL, "activo" BOOLEAN NOT NULL DEFAULT true, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ListaDesplegable_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "MovimientoInventario" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "tipo" TEXT NOT NULL, "materialId" TEXT, "descripcion" TEXT, "cantidad" INTEGER NOT NULL, "precioUnit" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL DEFAULT 0, "motivo" TEXT, "condominioId" TEXT, "userId" TEXT, "userName" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MovimientoInventario_pkey" PRIMARY KEY ("id"))',
    'CREATE TABLE IF NOT EXISTS "Comite" ("id" TEXT NOT NULL DEFAULT gen_random_uuid()::text, "nombre" TEXT NOT NULL, "cargo" TEXT NOT NULL DEFAULT \'Vocal\', "unidad" TEXT, "rut" TEXT, "telefono" TEXT, "email" TEXT, "foto" TEXT, "fechaInicio" TEXT, "fechaFin" TEXT, "estado" TEXT NOT NULL DEFAULT \'Activo\', "notas" TEXT, "condominioId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Comite_pkey" PRIMARY KEY ("id"))',
  ]
  let ok = 0, err = 0
  for (const s of sqls) {
    try { await p.$executeRawUnsafe(s); ok++ }
    catch (e: any) { if (e.message.includes('already exists')) ok++; else { err++; out.push(e.message.substring(0, 80)) } }
  }
  out.push(`${ok} tablas OK, ${err} err`)

  // Crear condominio si no existe
  try {
    await p.$executeRawUnsafe(`INSERT INTO "Condominio" ("id", "nombre", "direccion", "comuna", "ciudad", "activo", "updatedAt") VALUES ('cmo9f3x7j0000ktyeb0rzhwt9', 'Laguna Norte', 'Av. La Montaña Norte 3650, Lampa', 'Lampa', 'Santiago', true, NOW()) ON CONFLICT DO NOTHING`)
    out.push('Condominio creado')
  } catch (e: any) { out.push('Condominio: ' + e.message.substring(0, 50)) }

  // Crear usuarios con bcrypt
  const bcrypt = await import('bcryptjs').then(m => m.default).catch(() => null)
  if (bcrypt) {
    const users = [
      { email: 'admin@cyj.cl', pass: 'Admin123456', nombre: 'Administrador', apellido: 'Sistema', rol: 'admin' },
      { email: 'supervisor.test@cyj.cl', pass: 'Supervisor2026!', nombre: 'Supervisor', apellido: 'Test', rol: 'supervisor' },
      { email: 'usuario.test@cyj.cl', pass: 'Usuario2026!', nombre: 'Usuario', apellido: 'Test', rol: 'usuario' },
      { email: 'personal.test@cyj.cl', pass: 'Personal2026!', nombre: 'Personal', apellido: 'Test', rol: 'personal' },
      { email: 'auditor.test@cyj.cl', pass: 'Auditor2026!', nombre: 'Auditor', apellido: 'Test', rol: 'auditor' },
      { email: 'guardia.test@cyj.cl', pass: 'Guardia2026!', nombre: 'Guardia', apellido: 'Test', rol: 'guardia' },
    ]
    for (const u of users) {
      try {
        const hash = bcrypt.hashSync(u.pass, 10)
        await p.$executeRawUnsafe(`INSERT INTO "User" ("id", "email", "password", "nombre", "apellido", "rol", "activo", "condominioId", "updatedAt") VALUES (gen_random_uuid()::text, '${u.email}', '${hash}', '${u.nombre}', '${u.apellido}', '${u.rol}', true, 'cmo9f3x7j0000ktyeb0rzhwt9', NOW()) ON CONFLICT DO NOTHING`)
        out.push(`User ${u.email} creado`)
      } catch (e: any) { out.push(`User ${u.email}: ${e.message.substring(0, 50)}`) }
    }
  } else {
    out.push('bcrypt no disponible')
  }

  // Crear caja chica
  try {
    await p.$executeRawUnsafe(`INSERT INTO "CajaChica" ("id", "saldo", "saldoInicial", "condominioId", "updatedAt") VALUES (gen_random_uuid()::text, 500000, 500000, 'cmo9f3x7j0000ktyeb0rzhwt9', NOW()) ON CONFLICT DO NOTHING`)
    out.push('Caja chica creada')
  } catch (e: any) { out.push('Caja chica: ' + e.message.substring(0, 50)) }

  await p.$disconnect()
  return NextResponse.json({ success: true, out, tablas: ok })
}
